name: build-push-containers

on:
  push:
    branches:
      - 'main'
      - 'docker-action'


jobs:
  docker:
    runs-on: [self-hosted, linux, gpu]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to NVCR
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NVCR_USERNAME }}
          password: ${{ secrets.NVCR_PASSWORD }}   
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}      
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: stanfordvl/omnigibson-test:latest
          file: docker/prod.Dockerfile
