name: Sync OmniGibson-dev/master to OmniGibson/master

on:
  workflow_dispatch:
  schedule:
    # Sync repositories on the 1st and 15th of the month at 9 AM
    - cron:  "0 17 1,15 * *" 

jobs:
  sync-private-fork:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Sync OmniGibson-dev/master to OmniGibson/master
        if: github.repository == 'StanfordVL/OmniGibson-dev' && startsWith(github.ref, 'refs/tags')
        run:
          git push https://$PERSONAL_ACCESS_TOKEN:x-oauth-basic@github.com/StanfordVL/OmniGibson.git master:master
